### ISSUE TITLE
Asset importer plugin not working when materials are CryXML

### ISSUE THREAD

**Issue by draakuns** [Markemp/Cryengine-Importer#8] opened 2020-01-19 22:40 UTC
Hi,

not sure if issue or just not implemented, but here we go:

the materials (mtl) seems not to be parsed and the import fails. 
So my question: Is the importer supposed to work with CryXml mtl files or we just need to convert them to regular XML beforehand?

```
Import Asset.  Folder: C:\Juegos\scuncomp\Data\Objects\fps_weapons\weapons_v7\behr\rifle\p8ar\brfl_fps_behr_p8ar.dae
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_cryengine_importer\__init__.py", line 136, in execute
    return Cryengine_Importer.import_asset(context, **keywords)
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 526, in import_asset
    constants.materials.update(materials.create_materials(file, basedir, use_dds, use_tif))
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_cryengine_importer\materials.py", line 13, in create_materials
    mats = ET.parse(matfile)
  File "C:\Juegos\SC\blender\2.81\python\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Juegos\SC\blender\2.81\python\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 7

location: <unknown location>:-1

location: <unknown location>:-1
```

If I just convert the mtl on the same dir, it works... but makes nonsense because I suppose it should grab a lot more mtls from other references in the object dir...

Thanks in advance,
Draakuns

**Comment by Markemp** [comment] 2020-01-20 00:59
Oof... ok, this is a tough one.  mtl files in Cryengine are a big pain.  The converter program will attempt to find the related material file for any given model by looking for the name in the material chunk, a material file with the same name as the model in that directory, and a few other ways.  However (and this is a big issue with SC models), if the program cannot find the related material file, it will instead just create dummy materials for each of the materials used in the file, without trying to find the textures, etc (as that info is in the .mtl file).  

But... since this is a Cryengine Importer issue, the problem is a lot simpler to identify:  I haven't finished updating it to work with Blender 2.80+.  :(  I'm not sure when I'll be able to get back to finishing that up, but probably not until April at the earliest.

**Comment by draakuns** [comment] 2020-01-20 14:56
Hey @Markemp ,

ok, so I fully understand the mtl pain because SC in special they use a lot of strange materials from other directories.
But what I don't understand is the fact that if it fails with the message above, and I extract the plain xml material file instead of the CryXML one, it doesnt fail!
To me it seems like the CryXml deserializer is doing something nasty and the binary mtl files are not being read plain text. 
I tend to explain myself a bit... disastrous, so if you don't understand me just let me know so I can try to rephrase...

BR
Draakuns

**Comment by Markemp** [comment] 2020-01-22 00:49
The importer is using old 2.79 conventions, so that is why it is failing.  It's not an issue with the deserializer; just that the importer can't properly convert the XML. :(

**Comment by draakuns** [comment] 2020-01-22 07:57
Ok, there I wanted to go... 
So rework is needed, nice to know. (I will wait IF it arrives someday, not rushing here...)

Possible workaround: convert all CryXML material files to plain text, as far as I've been able to check... Will try converting all required mtl when time allows and will confirm if it serves the purpose.

Thanks a lot Mark!
Draakuns.

**Comment by Markemp** [comment] 2021-06-10 02:10
I think this is fixed?  I have the CryXml converter in the project, but haven't tested it against Star Citizen files.  Anyone able to check to see if it can read the .mtl or other SC "XML" files?

**Comment by Markemp** [comment] 2022-07-31 14:27
Closing as this is fixed.  Importer can handle CIG's binary XML files now.

**Closed by Markemp** 2022-07-31 14:27 UTC
